### ISSUE TITLE
release-approval should use Grabl token for creating the release branch

### ISSUE THREAD

**Issue by lolski** [graknlabs/build-tools#35]
This is much better than the current way where we have to add 'Checkout SSH keys' in CircleCI.

**Comment by vmax** [comment]
@lolski why is it better? we could accidentally leak it whereas SHA1 keys safety is the responsibility of CircleCI

**Comment by lolski** [comment]
It's better for us since we don't have to go through the extra step of adding a Checkout SSH keys.

The token definitely can be compromised, but we should just aim to not leak it with good security practice, which I think is not impossible. In case it did get leaked, invalidating the token should be an effective and simple solution to do.

If we found out that this is hard and error prone we need to rethink the whole approach of using Grabl token across our CI.

**Comment by lolski** [comment]
@vmax It's better for us since we don't have to go through the extra step of adding a Checkout SSH keys.

The token definitely can be compromised, but we should just aim to not leak it with good security practice, which I think is not impossible. In case it did get leaked, invalidating the token should be an effective and simple solution to do.

If we found out that this is hard and error prone we need to rethink the whole approach of using Grabl token across our CI.
