### ISSUE TITLE
Fix silent error output of process execution

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/build-tools#43]
We have reverted error outputs of process executions in two places:

https://github.com/graknlabs/build-tools/blob/2961df827b7842c1dbf125bab25250a7a6c12f3c/ci/sync-dependencies.py#L145

https://github.com/graknlabs/build-tools/blob/2961df827b7842c1dbf125bab25250a7a6c12f3c/checkstyle/test-coverage.py#L30

We need to fix them again so that errors are returned properly.

**Comment by lolski** [comment]
The request will fail with a `503 Service Unavailable` after exactly 30 seconds:
```
$ time curl --silent --show-error --fail -X POST --data '{ ... }' \
  -H 'Content-Type: application/json' \
  -H 'X-Hub-Signature: ...' \
  https://grabl.grakn.ai/sync/dependencies

curl: (22) The requested URL returned error: 503 
       30.20 real         0.02 user         0.00 sys
```

It is a Heroku's behavior and is non-configurable, according to [their documentation](https://devcenter.heroku.com/articles/request-timeout):

_The timeout value is not configurable. If your server requires longer than 30 seconds to complete a given request, we recommend moving that work to a background task or worker to periodically ping your server to see if the processing request has been finished._

Therefore, the right behavior is for us to make Grabl this request execute in the background

**Comment by haikalpribadi** [comment]
Okay then I'm closing this issue, @lolski . I've created a new for the actual solution on Grabl: https://github.com/graknlabs/grabl/issues/22
