### ISSUE TITLE
Create CI tool to Increment version number after a release

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/build-tools#47]
We want `//ci:sync-version` to bump the version of the LOCAL repository in which it is executed in. What that means is that if the current repository has `VERSION` file containing `X.Y.Z`, when `//ci:sync-version` is called, it will change the content of the file to be `X.Y.Z+1`. 

E.g. `VERSION` file content changes from `1.5.2` to `1.5.3`.

Now, we have the option of:
a) provide `/path/to/VERSION` as arguments to the `bazel run` command (e.g. `-- /path/to/VERSION`)
b) provide `/path/to/VERSION` as argument in the target declaration in the `BUILD` file
c) not provide `/path/to/VERSION` as it should always be expected (and thus hard-coded) to be at the root of every repository.

**Comment by haikalpribadi** [comment]
Let's call it `//ci:sync-version`

**Comment by vmax** [comment]
@haikalpribadi could you provide more context on how it would be used?
i.e.
- given `VERSION` file
- when running `bazel run @graknlabs_build_tools//ci:sync-version` (arguments?)
- then …

**Comment by haikalpribadi** [comment]
sorry for not elaborating the description in this issue @vmax:

We want `//ci:sync-version` to bump the version of the LOCAL repository in which it is executed in. What that means is that if the current repository has `VERSION` file containing `X.Y.Z`, when `//ci:sync-version` is called, it will change the content of the file to be `X.Y.Z+1`. 

E.g. `VERSION` file content changes from `1.5.2` to `1.5.3`.

Now, we have the option of:
a) provide `/path/to/VERSION` as arguments to the `bazel run` command (e.g. `-- /path/to/VERSION`)
b) provide `/path/to/VERSION` as argument in the target declaration in the `BUILD` file
c) not provide `/path/to/VERSION` as it should always be expected (and thus hard-coded) to be at the root of every repository.

Which one should we go for? @lolski ?

**Comment by vmax** [comment]
@haikalpribadi @lolski I'd go with option

>c) not provide /path/to/VERSION as it should always be expected (and thus hard-coded) to be at the root of every repository.

and just throw exception if `VERSION` is not there

**Comment by haikalpribadi** [comment]
I forgot to mention my preference above. I actually think we should go with option B. That way it could be both:
a) easy to use (no need any arguments when calling `bazel run`)
b) explicit and flexible (we can update other version files located elsewhere in future repos)

what do you think @lolski ?

**Comment by lolski** [comment]
I'd also go with option c). `build-tools` is for use within Grakn Labs only and here we always expect VERSION file to be located at root.

Also, according to the team meeting on Tuesday, there is an argument from @marco-scoppetta against automating the version bump (and also milestone creation). Let's resolve the argument before we move forward with the implementation @haikalpribadi @vmax ?

**Comment by lolski** [comment]
If we wanna go with b), we will need to create a `ci:sync-version` target in every repo instead of having just one in `build-tools`, right @haikalpribadi @vmax ?

**Comment by vmax** [comment]
@lolski yes. implementation could be shared via `@graknlabs_build_tools` though. something like:

```
py_binary(
    name= "sync_version",
    srcs = ["@graknlabs_build_tools//ci:sync-version.py"],
    data= ["//:VERSION"],
    args = ["$(location //:VERSION)"]
)
```

**Comment by haikalpribadi** [comment]
okay let's do option B, then, @lolski @vmax
