### ISSUE TITLE
Use Grabl's credential when deleting the release branch in the release-cleanup CI job of every repository

### ISSUE THREAD

**Issue by lolski** [graknlabs/build-tools#92]
We need to use Grabl's API key credential when deleting the release branch in the `release-cleanup` CI job of every repository. Right now, the deletion is done using a separate SSH key and given that we've already got Grabl's API key credential, we should use that instead:

```
release-cleanup:
  git push --delete https://$REPO_GITHUB_TOKEN@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME $CIRCLE_BRANCH
```

PS: This issue needs to be resolved in every repository in Graknlabs. In order to not have to create multiple identical issues, I've decided to create this issue in `build-tools`.

**Comment by lolski** [comment]
It's been fixed in the following repository:
- kglib

**Comment by vmax** [comment]
I've checked all repos that we're doing a release on and the only one missing this approach was `common`. Once graknlabs/common#5 is merged, work on this issue is concluded, so I'm closing it.
