### ISSUE TITLE
//release-validate-deps

### ISSUE THREAD

**Issue by haikalpribadi** [graknlabs/build-tools#93]
Problem to Solve

Given that Grakn now has a multi-repo architecture, we need to make sure that a repository is released if it depends on other repositories by tag, rather than commit. If a dependency is referenced by commit, that means that dependency is still in "snapshot" mode, and only available in the `*-snapshot` distribution repos.

Proposed Solution

Introduce @graknlabs_build_tools//release-validate-deps CI tool to validate whether a given repository is releasable by checking that all of its releasable Grakn Labs dependencies are referenced by tag. An attempt to release a repository which depends on snapshot dependencies should produce a failure.

**Comment by vmax** [comment]
Fixed by #95
